config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "articles#index"

  resources :articles do
    post "like", to: "articles#like"
    resources :comments do
      post "like", to: "comments#like"
    end
  end

  resources :users

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible, Likeable

  belongs_to :article
  belongs_to :user
  has_many :likes, dependent: :destroy

  def create_like(user_id)
    self.likes.create(user_id: user_id, comment_id: self.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user
  def create
    # find the article that was commented
    @article = Article.find(params[:article_id])
    # create a new comment (interesting that you can create the object
    # from the list of comments from article)
    @comment = @article.comments.create(comment_params)
    @comment.user = User.find(session[:user_id])

    @comment.save
    # redirect to the article to which the comment was added
    redirect_to article_path(@article)
  end

  def destroy
    # get the article with the id
    @article = Article.find(params[:article_id])
    # find the comment with the provided id
    @comment = @article.comments.find(params[:id])
    # delete te comment
    @comment.destroy

    # redirect to the article
    redirect_to article_path(@article), status: :see_other
  end

  def like
    @comment = Comment.find(params[:comment_id])

    if @comment.like(session[:user_id])
      redirect_back(fallback_location: root_path)
    else
      head :unprocessable_entity
    end
  end

  private
    def comment_params
      # allow only commenter and body when creating a comment
      params.require(:comment).permit(:body, :status)
    end
end

app/views/comments/_comment.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_importmap_tags %>

<%# can be seen only if private and the user is the author of the article or the author of the comment %>
<% unless comment.archived? or 
((comment.article.user.id != session[:user_id] and comment.user.id != session[:user_id]) and comment.private?)%>

  <p>
    Comment by
    <strong> <%= comment.user.username %> </strong> :
    <%= comment.body %>

    <% if comment.user.id == session[:user_id] %>
      <span class="mb-1">
        <%= link_to [comment.article, comment], data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } do %>
          <%= image_tag('delete.png', style: 'height:18px;width:auto;')%>
        <% end %>
      </span>
    <% end %>

    <td><%= link_to article_comment_like_path(comment.article, comment.id), data: { turbo_method: :post } do%>
      <% if comment.likes.find { |like| like.user_id == session[:user_id] } %>
        <%= image_tag('like.png', style: 'height:18px;width:auto;')%>
      <% else %>
        <%= image_tag('not_liked.png', style: 'height:18px;width:auto;')%>
      <% end %>

    <% end %></td>
    <%= comment.likes.count %>

  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ article, article.comments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
    <%= form.submit %>
  </div>

<% end %>