config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "articles#index"

  resources :articles do
    post "like", to: "articles#like"
    resources :comments do
      post "like", to: "comments#like"
    end
  end

  resources :users

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible, Categorized, Likeable
  # mixin with Visible, inherits the methods and properties

  belongs_to :user

  # has a one to many relationship with comment, an article has
  # multiple comments. When article deleted remove it's comments as well
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy

  # must have a title
  validates :title, presence: true

  # must have a body
  validates :body, presence: true, length: { minimum: 10 }

  def create_like(user_id)
    self.likes.create(user_id: user_id, article_id: self.id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authorize_own_article, :authenticate_user, :authorize_private_article
  # do not authorize your own article for show, index, new and create
  skip_before_action :authorize_own_article, only: [ :show, :index, :new, :create, :like ]
  skip_before_action :authorize_private_article, only: [ :index, :new, :create, :like ]
  def index
    @articles = Article.all
  end

  def show
    # set the variable article to the value from database,
    # take the id of it from the parameters passed by user
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    user = User.find(session[:user_id])

    @article = user.articles.create(article_params)

    # if saved successfully then redirect to it
    if @article
      redirect_to @article
    # if not saved successfuly return status unprocessable entity
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # sets the @article instance variable to the article from the database
    # such that when edit page is accessed form fields are populated already
    @article = Article.find(params[:id])
  end

  def update
    # get the article from the database
    @article = Article.find(params[:id])

    # update with the provided user parameters
    if @article.update(article_params)
      # if success redirect to the article
      redirect_to @article
    else
      # else return 422
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # get article from database
    @article = Article.find(params[:id])

    # delete the article from database
    @article.destroy

    # return to root
    redirect_to root_path, status: :see_other
  end

  def like
    @article = Article.find(params[:article_id])

    if @article.like(session[:user_id])
      redirect_back(fallback_location: root_path)
    else
      head :unprocessable_entity
    end
  end

  private
    # define what parameters are allowed to be passed by user
    # in the request. permit title and body from article
    def article_params
      params.require(:article).permit(:title, :body, :status, :category)
    end

    # allow to edit or delete only your own articles
    def authorize_own_article
      @article = Article.find(params[:id])
      if @article.user.id != session[:user_id]
        redirect_to root_path, status: :unauthorized
      end
    end

    # allow to view only your own articles if they are private
    def authorize_private_article
      @article = Article.find(params[:id])
      if @article.user.id != session[:user_id] and @article.private?

        redirect_to root_path, status: :unauthorized
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articlecard.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_importmap_tags %>

<%= link_to article do %>
    <div class="p-3 bg-light" style="width:30%; margin-top:10px">
        Name : <%= article.title %>
        <br>
        Author : <%= article.user.username %>
        <br>
        Category : <%= article.category %>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%# reusable, uses article instead of @article to not be dependent on an instance variable %>
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
  </div>

  <div>
    <%= form.label :category %><br>
    <%= form.select :category, Categorized::VALID_CATEGORIES, selected: article.category || 'Nature' %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_importmap_tags %>

<div class="container-fluid p-5 text-center">
    <h1> The blog has <%= Article.public_count %> articles and counting! </h1> 
</div>

<ul class="p-5">
    <% @articles.each do |article| %>
        <% unless article.archived? or (article.user.id != session[:user_id] and article.private?)%>
            <%= render "articles/articlecard", article: article%>
        <% end %>
    <% end %>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_importmap_tags %>

<div class="container-fluid p-5 bg-primary text-white text-center">

  <div class="col-12 d-flex justify-content-beginning">
    <%= link_to articles_path do %>
      <%= image_tag('back.png', style: 'height:30px;width:auto;')%>
    <% end %>
  </div>

  <h1><%= @article.title %></h1>
  <h3>Category: <%= @article.category %></h3>
  <p>Author: <%= @article.user.username %></p>

  <% if @article.user.id == session[:user_id] %>
    <span class="mb-1">
      <%= link_to edit_article_path(@article) do %>
        <%= image_tag('edit.png', style: 'height:30px;width:auto;')%>
      <% end %>
    </span>

    <span class="mb-1">
      <%= link_to article_path(@article), data: {
                        # use delete method instead of get 
                        turbo_method: :delete,
                        # adds a confirmation dialouge
                        turbo_confirm: "Are you sure?"
                      }  do %>
        <%= image_tag('delete.png', style: 'height:30px;width:auto;')%>
      <% end %>
    </span>
  <% end %>

  <%= link_to article_like_path(@article), data: { turbo_method: :post } do%>
    <% if @article.likes.find { |like| like.user_id == session[:user_id] } %>
      <%= image_tag('like.png', style: 'height:18px;width:auto;')%>
    <% else %>
      <%= image_tag('not_liked.png', style: 'height:18px;width:auto;')%>
    <% end %>
  <% end %>

  <%= @article.likes.count %>

</div>
  
<div class="container">
    
  <p class="mt-3"><%= @article.body %></p>

  <div class="mb-2"><h2>Comments</h2></div>

  <%= render @article.comments %>

  <%= render "comments/form", article: @article%>

</div>