config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "articles#index"

  resources :articles do
    post "like", to: "articles#like"
    resources :comments do
      post "like", to: "comments#like"
    end
  end

  resources :users

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :articles
  has_many :comments
  validates :email, presence: true
  validates_format_of :email,  with: /\A[^@\s]+@[^@\s]+\z/, message: "Must be a valid email address"
  validates :password_digest, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email)
    end
end

app/views/users/_form.html.erb
<%# reusable, uses article instead of @article to not be dependent on an instance variable %>
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
    <% user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_area :email %><br>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_usernavbar.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_importmap_tags %>

<%= link_to edit_user_path(user) do %>
    
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= javascript_importmap_tags %>

<div class="container-fluid p-5 bg-primary text-white text-center">

    <div class="col-12 d-flex justify-content-beginning">
    <%= link_to articles_path do %>
        <%= image_tag('back.png', style: 'height:30px;width:auto;')%>
    <% end %>
    </div>

    <h1><%= @user.username %></h1>

    <span class="mb-1">
        <%= link_to edit_user_path(@user) do %>
            <%= image_tag('edit.png', style: 'height:30px;width:auto;')%>
        <% end %>
    </span>
</div>